catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('animal_list/', views.AnimalListView.as_view(), name='animal_list'),
    path('animal_detail/<int:pk>', views.AnimalDetailView.as_view(), name='animal_detail'),
    path('animal/create/', views.AnimalCreate.as_view(), name='animal_create'),
    path('animal/<int:pk>/update/', views.AnimalUpdate.as_view(), name='animal_update'),
    path('animal/<int:pk>/delete/', views.animal_delete, name='animal_delete'),
    path('animal_images/', views.animal_image_list, name='animal_image_list'),

]

fluffnscales/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls import include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('register.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


register/urls.py
from django.urls import path
from . import views
urlpatterns = [
 path('register/', views.register, name='register'),
]

catalog/models.py
from django.db import models
from django.urls import reverse  # Used to generate URLs by reversing the URL patterns
import uuid  # Required for unique book instances
from django.contrib.auth.models import User
from datetime import date


class Animal(models.Model):
    """Model representing an animal."""
    animal_name = models.CharField(max_length=100)
    animal_image = models.ImageField(upload_to='images/', null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    class Meta:
        ordering = ['animal_name']

    def get_absolute_url(self):
        """Returns the URL to access a particular animal instance."""
        return reverse('animal_detail',args=[str(self)])

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.animal_name}'

register/models.py
from django.db import models

# Create your models here.

register/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ["username", "first_name", "last_name", "email", "password1", "password2"]

catalog/views.py
from .models import Animal
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.urls import reverse
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView, UpdateView
from django.contrib import messages
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required


def index(request):
    return render(request, 'catalog/index.html')


class AnimalDetailView(LoginRequiredMixin, generic.ListView):
    model = Animal


class AnimalCreate(CreateView):
    model = Animal
    fields = ['animal_name', 'animal_image']

    def form_valid(self, form):
        post = form.save(commit=False)
        post.save()
        return HttpResponseRedirect(reverse('animal_image_list'))


class AnimalUpdate(UpdateView):
    model = Animal
    fields = ['animal_name', 'animal_image']

    def form_valid(self, form):
        post = form.save(commit=False)
        post.save()
        return HttpResponseRedirect(reverse('animal_list'))


def animal_delete(request, pk):
    animal = get_object_or_404(Animal, pk=pk)
    animal.delete()
    messages.success(request, (animal.animal_name + " has been deleted"))
    return redirect('animal_list')


def animal_image_list(request):
    animals = Animal.objects.exclude(animal_image='').order_by('animal_name').select_related('user')
    return render(request, 'catalog/animal_image_list.html', {'animals': animals})


class AnimalListView(LoginRequiredMixin, generic.ListView):
    model = Animal
    template_name = 'catalog/animal_list.html'
    login_url = 'login'

    def get_queryset(self):
        return Animal.objects.filter(user=self.request.user)



register/views.py
from django.shortcuts import render, redirect
from .forms import RegisterForm
from django.contrib.auth.models import User, Group


# Create your views here.
def register(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            uname = form.cleaned_data['username']
            form.save()
            # get the new user info and set the group for this user to LibraryMember
            user = User.objects.get(username=uname)
            lib_group = Group.objects.get(name='LibraryMember')
            user.groups.add(lib_group)
            user.save()
            return redirect('login')
        return redirect("index")
    else:
        form = RegisterForm()

    return render(request, "catalog/register.html", {"form": form})

catalog/templates/catalog/animal_detail.html
{% extends "catalog/base.html" %}
{% block content %}
    <div class="animallist" style="padding-left: 50px;">
    <p><strong>Animal Name</strong> <a href="">{{ animal.animal_name }}</a></p>
    <div>
    {% if animal.animal_image %}
    <img src="{{ animal.animal_image.url }}">
    {% endif %}
 </div>
{% endblock %}
</div>

catalog/templates/catalog/animal_form.html
{% extends "catalog/base.html" %}
{% load crispy_forms_tags %}
{% load crispy_forms_filters %}

{% block title %}Add Animal{% endblock %}

{% block content %}
  <style>
    /* Set a max-width for the form */
    form {
      max-width: 500px;
      width: 303px;
      margin: 0 auto;
    }

    /* Add padding to form elements */
    .form-group {
      padding: 10px;
    }

    /* Style the submit button */
    input[type="submit"] {
    background-color: #4d90fe;
    border: none;
    border-radius: 5px;
    color: #fff;
    cursor: pointer;
    font-size: 16px;
    font-weight: bold;
    margin-top: 10px;
    padding: 10px;
    width: 100%;
  }
  input[type="submit"]:hover {
    background-color: #357ae8;
  }

    /* Style the file input */
    input[type="file"] {
      border: none;
      padding: 5px;
      background-color: #f5f5f5;
    }

    /* Style the form labels */
    label {
      display: block;
      margin-bottom: 5px;
      font-weight: bold;
    }

    /* Style form input fields */
    input[type="text"], input[type="password"], select {
      width: 100%;
      padding: 10px;
      border: none;
      border-bottom: 1px solid #ddd;
      background-color: #f5f5f5;
    }

    /* Style form error messages */
    .errorlist {
      color: red;
    }
  </style>

  {% if perms.catalog.add_animal or perms.catalog.edit_animal %}
    <form action="" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form|crispy }}
      <input type="submit" value="Upload">
    </form>
  {% else %}
    You do not have permission to access this feature. <a href="{% url 'index' %}">Home</a>
  {% endif %}
{% endblock %}

catalog/templates/catalog/animal_image_list.html
{% extends "catalog/base.html" %}
{ % load static %}
{% block content %}
 <style>
/* Make the body full-screen */
body {
  height: 100%;
  margin: 0;
}

/* Set a background color */
body {
  background-color: #FAFAFA;
}

/* Center the content */
.container {
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  margin-top: 30px;
}

/* Style the heading */
h1 {
  font-size: 24px;
  font-weight: bold;
  text-align: left;
  margin-bottom: 10px;
  padding-left: 20px;
}

/* Style the animal container */
.animal-container {
  display: flex;
  flex-wrap: wrap;

  justify-content: space-between;
  margin: 0 20px;
}

/* Style each animal card */
.animal-card {
  width: calc(33.33% - 10px);
  margin-bottom: 20px;
  box-shadow: 0px 1px 3px rgba(0, 0, 0, 0.12), 0px 1px 2px rgba(0, 0, 0, 0.24);
  border-radius: 5px;
  overflow: hidden;

}

.animal-card:hover {
  cursor: pointer;
  transform: scale(1.02);
  transition: all 0.2s ease-in-out;
}

.animal-card img {
  width: 100%;
  height: 100%;
  object-fit: contain;
  background-color: white;

}


/* Style the animal name */
.animal-name {
  margin-top: 10px;
  font-weight: bold;
  text-align: center;
  color: black;
  font-family: Helvetica;
  font-size: 20px;
}



</style>
<div class="container">
<h1>Discover </h1>
<div class="animal-container" >

{% if animals %}
  {% for animal in animals %}
    <div class="animal-card">
      <div class="animal-name">{{ animal.animal_name }}</div>
      <img src="{{ animal.animal_image.url }}" alt="{{ animal.animal_name }}">
    </div>
  {% endfor %}
{% else %}
  <p>There are no posts :(</p>
{% endif %}

</div>
</div>

{% endblock %}

catalog/templates/catalog/animal_list.html
{% extends "catalog/base.html" %}

{% block content %}
<h1>My Posts</h1>
<ul>
{% for animal in object_list %}
    <li>
        <a href="{{ animal.get_absolute_url }}">{{ animal.animal_name }}</a>
    </li>
{% empty %}
    <li>No posts found.</li>
{% endfor %}
</ul>
{% endblock %}

catalog/templates/catalog/author_delete.html
{% extends "catalog/base.html" %}
{% block content %}
 {% if perms.catalog.delete_animal %}
 <h1>Delete Animal {{ animal.animal_name }}</h1>
 <form method="Post">
 {% csrf_token %}
 <input type="submit" class="btn btn-danger" 
value="Delete">
 <a href="{% url 'index' pk=animal.id %}
">Cancel</a>
 </form>
 {% else %}
 You do not have permission to access this feature
 <a href="{% url 'index' %}">Home</a>
 {% endif %}
{% endblock %}

catalog/templates/catalog/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
 <meta charset="utf-8">
 <meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />

 <title>{% block title %}Fluff n Scales{% endblock %}</title>
</head>
<body>
<nav>
  <ul>
    <li {% if request.resolver_match.view_name == 'index' %}class="active"{% endif %}>
      <a href="{% url 'index' %}"><i class="fas fa-paw"></i> Fluff N' Scales</a>
    </li>

    {% if user.is_authenticated %}
      <li {% if request.resolver_match.view_name == 'animal_create' %}class="active"{% endif %}>
        <a class="nav-link" href="{% url 'animal_create' %}"><i class="fas fa-plus-circle"></i> New Post</a>
      </li>
      <li {% if request.resolver_match.view_name == 'animal_image_list' %}class="active"{% endif %}>
        <a class="nav-link" href="{% url 'animal_image_list' %}"><i class="fas fa-images"></i> Feed</a>
      </li>
      <li {% if request.resolver_match.view_name == 'logout' %}class="active"{% endif %}>
        <a href="{% url 'logout' %}"><i class="fas fa-sign-out-alt"></i> {{ user.first_name }}{{ user.last_name }} Logout</a>
      </li>
    {% else %}
      <li {% if request.resolver_match.view_name == 'login' %}class="active"{% endif %}>
        <a href="{% url 'login' %}"><i class="fas fa-sign-in-alt"></i> Login</a>
      </li>
      <li {% if request.resolver_match.view_name == 'register' %}class="active"{% endif %}>
        <a href="{% url 'register' %}"><i class="fas fa-user-plus"></i> Sign Up</a>
      </li>
    {% endif %}
  </ul>
</nav>

<div class="container1" >
 <br/>
 {% block content %}
 {% endblock %}
</div>

</body>
<style>
 body{
  background-color: white;
    font-family: Arial, sans-serif;
    font-size: 18px;
    margin: 0;
 }
nav {
  font-family: Helvetica;
  background-color: #01257D;
  overflow: hidden;
}

nav ul {
  margin: 0;
  padding: 0;
  list-style: none;
}

nav li {
  float: left;
}

nav li a {
  display: block;
  color: white;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
}

nav li a:hover {
  background-color: #333;
}

.active {
  background-color: blue;
}

</style>
</html>

catalog/templates/catalog/index.html
{% extends 'catalog/base.html' %}
{% load static %}
{% block content %}
    <style>
   *{
  text-align: center;

}

body{
  font-family: Arial, Helvetica, sans-serif;
}

h1{
  color: orange;
  margin-bottom: 8px;
  font-size: 60px;
}
h2{
  font-size: 35px;
  color: blue;
  padding: 2px;
}
p{
  font-size: 25px;
  margin-bottom: 2px;
}
.dog1{
  height: 350px;
  width: auto;
  padding-left: 100px;
  padding-right: 100px;
}
.dog2{
  height: 350px;
  width: auto;
  padding-left: 100px;
  padding-right: 100px;
  padding-top: 0;
}

    </style>
<div class="welcome" style="text-align: left;font-size: 25px;">
    {% if user.is_authenticated %}
        Welcome, {{ user.first_name }} {{ user.last_name }}
    {% endif %}
</div>
<h1>Fluff N' Scales</h1>
<h2>We Love Animals!</h2>
{% load static %}
<img class ="dog1" src="{% static 'dog1.jpg' %}">

<img class ="dog2" src="{% static 'dog2.jpg' %}">
<br>

{% endblock %}

catalog/templates/catalog/register.html

{% extends "catalog/base.html" %}
{% block title %}Create an Account{% endblock %}
{% load crispy_forms_tags %}
{% load crispy_forms_filters %}
{% block content %}


<style>
 /* Center the content */
 body{
  background-color: white;
    font-family: Arial, sans-serif;
    font-size: 18px;
    margin: 0;
 }
.form-group {
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  margin-top: 30px;
}

/* Style the heading */
h1 {
  font-size: 24px;
  font-weight: bold;
  text-align: left;
  margin-bottom: 10px;
  padding-left: 20px;
}

/* Style the form */
form {
  width: 50%;
  margin: auto;
 text-align: center;
}

/* Style the form fields */
input[type="text"]{
  width: 250px;
  padding: 10px;
  margin-bottom: 20px;
  border: none;
  border-radius: 5px;
  background-color: #f2f2f2;

}
input[type="email"]{
  width: 250px;
  padding: 10px;
  margin-bottom: 20px;
  border: none;
  border-radius: 5px;
  background-color: #f2f2f2;

}
input[type="password"] {
  width: 250px;
  padding: 10px;
  margin-bottom: 20px;
  border: none;
  border-radius: 5px;
  background-color: #f2f2f2;
}

input[type="text"]:focus,
input[type="email"]:focus,
input[type="password"]:focus {
  outline: none;
  box-shadow: 0px 0px 5px #4d90fe;
}

/* Style the form button */
button[type="submit"] {
  width: 150px;
  padding: 10px;
  border: none;
  border-radius: 5px;
  background-color: #4d90fe;
  color: #fff;
  font-size: 16px;
  cursor: pointer;
}

button[type="submit"]:hover {
  background-color: #357ae8;
}

/* Style the login link */
p {
  margin-top: 20px;
  text-align: center;
}

a {
  color: #4d90fe;
  text-decoration: none;
}

a:hover {
  text-decoration: underline;
}
ul{
 text-align: left;
}

</style>
 <form method="POST" class="form-group">
 {% csrf_token %}
 {{ form|crispy }}
 <button type="submit" class="btn btn-success">Register</button>
 </form>
 <p><strong>Already have an account?</strong>
 <a href="{% url 'login' %}"> Login Now</a>
 </p>
{% endblock %}
</html>

catalog/templates/catalog/user_animal_list.html
{% extends "catalog/base.html" %}

{% block content %}
<h1>Your Books</h1>
{% if animals %}
    <ul>
    {% for animal in animals %}
        <li><a href="{{ animal.get_absolute_url }}">{{ animal.animal_name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>You have not uploaded any books.</p>
{% endif %}
{% endblock %}